// Generated by Selenium IDE
package com;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

public class LoginTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("https://demoqa.com/login");
    driver.manage().window().setSize(new Dimension(1529, 993));
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("pedrito123");
    driver.findElement(By.id("password")).sendKeys("Pedrito123!");
    driver.findElement(By.id("login")).click();
  }
}
