// Generated by Selenium IDE
package com;

import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.AfterMethod;

import java.io.FileInputStream;
import java.io.IOException;

import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

public class LoginTest {
    private WebDriver driver;
    JavascriptExecutor js;

    @BeforeMethod
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
    }

    @AfterMethod
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void loginExitoso() {
        driver.get("https://demoqa.com/login");
        driver.manage().window().setSize(new Dimension(1529, 993));
        driver.findElement(By.id("userName")).click();
        driver.findElement(By.id("userName")).sendKeys("pedrito123");
        driver.findElement(By.id("password")).sendKeys("Pedrito123!");
        driver.findElement(By.id("login")).click();
    }

    @DataProvider(name = "loginData")
public Object[][] getLoginData() throws IOException {
    FileInputStream fis = new FileInputStream("src/test/resources/datos/LoginData.xlsx");
    XSSFWorkbook workbook = new XSSFWorkbook(fis);
    XSSFSheet sheet = workbook.getSheetAt(0);

    int rowCount = sheet.getPhysicalNumberOfRows();
    int colCount = sheet.getRow(0).getLastCellNum();

    Object[][] data = new Object[rowCount - 1][colCount];

    for (int i = 1; i < rowCount; i++) {
        for (int j = 0; j < colCount; j++) {
            data[i - 1][j] = sheet.getRow(i).getCell(j).toString();
        }
    }

    workbook.close();
    fis.close();
    return data;
}
    @Test(dataProvider = "loginData")
public void loginFallido(String username, String password) {
    driver.get("https://demoqa.com/login");
    driver.findElement(By.id("userName")).sendKeys(username);
    driver.findElement(By.id("password")).sendKeys(password);
    driver.findElement(By.id("login")).click();
}
}

