// Generated by Selenium IDE
package com;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.Dimension;

public class RegistroTest {
  private WebDriver driver;
  private RegisterPage register;

  @BeforeClass
  public void setUp() {
    driver = new FirefoxDriver();
    register = new RegisterPage(driver);
  }

  @AfterClass
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registro() {
    driver.get("https://demoqa.com/login");
    driver.manage().window().setSize(new Dimension(1529, 945));

    register.createNewUser();
    register.setFirstname("Pedro");
    register.setLastname("Pascal");
    register.setUsername("pedrito12");
    register.setPassword("Pedrito123!");

    // Si el reCAPTCHA está presente, no se puede interactuar automáticamente
    // driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();

    register.register();

    // Esperar 2 segundos por si aparece mensaje de error
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    register.saveScreenshot();
  }
}
