// Generated by Selenium IDE
package com;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import java.io.File;
import java.io.IOException;
import org.apache.commons.io.FileUtils;

public class RegistroTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registro() {
    driver.get("https://demoqa.com/login");
    driver.manage().window().setSize(new Dimension(1529, 945));

    //Hacer scroll hasta que el elemento esté visible, ya que puede ser tapado por publicidad
    WebElement newUserBtn = driver.findElement(By.id("newUser"));
js.executeScript("arguments[0].scrollIntoView(true);", newUserBtn);
newUserBtn.click();

    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Pedro");
    driver.findElement(By.id("lastname")).sendKeys("Pascal");
    driver.findElement(By.id("userName")).sendKeys("pedrito12");
    driver.findElement(By.id("password")).sendKeys("Pedrito123!");
    //Si el reCAPTCHA está presente, no se puede interactuar automáticamente
    //driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();

    // Scroll hasta el botón de registro
    WebElement registerBtn = driver.findElement(By.id("register"));
    js.executeScript("arguments[0].scrollIntoView(true);", registerBtn);
    registerBtn.click();

    // Esperar 2 segundos por si aparece mensaje de error
    try {
        Thread.sleep(2000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }

    // Capturar screenshot
    File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
    try {
        FileUtils.copyFile(screenshot, new File("screenshots/registro_error.png"));
    } catch (IOException e) {
        e.printStackTrace();
    }
  }
}
